version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    platform: linux/amd64
    network_mode: host
    volumes:
      - ./test-results:/test-results
      - ./target:/app/target
      - .:/app:ro
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5433
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3307
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3308
    profiles: ["tests"]

  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["dbs"]

  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "--password=testpass"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["dbs"]

  mariadb:
    image: mariadb:10.11
    platform: linux/amd64
    environment:
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "--password=testpass"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["dbs"]

